name: Publish To Docker Hub

on:
  push:
  workflow_dispatch:

jobs:

  cv_docker_publish:
    name: CV Docker Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Branch
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Get Version
        run: echo "VERSION=${GITHUB_REF##*/}.$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: valaz
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: valaz/cv:${{ env.VERSION }}, valaz/cv:${{ env.BRANCH }}.latest
          platforms: linux/amd64,linux/arm64
          build-args: |
            BRANCH=${{ env.BRANCH }}