---
name: 'Deploy to Dokku'

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@dale.valiev.top:22/cv'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
